from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.DEVICE = "cuda"
_C.MODEL.NO_DISTRIBUTION = False
_C.MODEL.RESUME_EPOCH = -1
_C.MODEL.INFERENCE = "origin"
_C.MODEL.NAME = "unetr"
_C.MODEL.PRETRAIN_MODEL_PATH = ""
_C.MODEL.NOISY = ""

_C.LOGGER = CN()
_C.LOGGER.NAME = ""
_C.LOGGER.LEVEL = 20
_C.LOGGER.STREAM = "stdout"

_C.SAVE_DIR = CN()
_C.SAVE_DIR.LOG = "output/log"
_C.SAVE_DIR.TENSORBOARD = "output/tensorboard"
_C.SAVE_DIR.MODEL = "output/saved_models"

_C.DATA = CN()
_C.DATA.NAME = "VESSEL"
_C.DATA.TRAIN_DATA = []
_C.DATA.VAL_DATA = []
_C.DATA.TRAIN_BATCHSIZE = 32
_C.DATA.VAL_BATCHSIZE = 32
_C.DATA.CACHE_NUM = 2
_C.DATA.CACHE_RATE = 1.0
_C.DATA.NUM_WORKERS = 2
_C.DATA.SAMPLERS = ""
_C.DATA.PERSISTENT_WORKERS = False

_C.TEST = CN()
_C.TEST.MODEL_PATH = "/data1/zzh/VesselSegModel/3DMISSFormer/models/model_best.pth"
_C.TEST.MODEL_DIR = ""

_C.INPUT = CN()
_C.INPUT.MODE = "RGB"
_C.INPUT.PIXEL_MEAN = [0.485, 0.456, 0.406]
_C.INPUT.PIXEL_STD = [0.229, 0.224, 0.225]
_C.INPUT.DATA_SHAPE = [3, 224, 224]
_C.INPUT.NUM_CLASSES = 1

_C.OUTPUT = CN()
_C.OUTPUT.NUM_CLASSES = 2
_C.OUTPUT.SAVEFILEDIR = "/data1/zzh/VesselSegModel/3DMISSFormer/test"

_C.SOLVER = CN()
_C.SOLVER.LOSS_TYPE = "dice"
_C.SOLVER.NUM_EPOCHS = 60
_C.SOLVER.STEP_PER_EPOCH = 2500
_C.SOLVER.OPTIMIZER_NAME = "Adam"
_C.SOLVER.MAX_IERS = 60
_C.SOLVER.STEPS = [30, 50]
_C.SOLVER.WEIGHT_DECAY_BIAS = 0.0005
_C.SOLVER.GAMMA = 0.1
_C.SOLVER.WARMUP_FACTOR = 0.01
_C.SOLVER.WARMUP_ITERS = 10
_C.SOLVER.WARMUP_METHOD = "linear"
_C.SOLVER.LR_TYPE = "warmup_steplr"
_C.SOLVER.STEP_SIZE = 10
_C.SOLVER.BASE_LR = 3e-4
_C.SOLVER.WEIGHT_DECAY = 0.0005
_C.SOLVER.MOMENTUM = 0.99
_C.SOLVER.VALIDATE_FREQ = 1
_C.SOLVER.SAVE_FREQ = 10
_C.SOLVER.AMP = True

_C.MODEL.UNETR = CN()
_C.MODEL.UNETR.FEATURE_SIZE = 16
_C.MODEL.UNETR.HIDDEN_SIZE = 768
_C.MODEL.UNETR.MLP_DIM = 3072
_C.MODEL.UNETR.NUM_HEADS = 12
_C.MODEL.UNETR.POS_EMBED = "perceptron"
_C.MODEL.UNETR.NORM_NAME = "instance"
_C.MODEL.UNETR.CONV_BLOCK = True
_C.MODEL.UNETR.RES_BLOCK = True
_C.MODEL.UNETR.DROPOUT_RATE = 0.0


_C.MODEL.MISSFORMER = CN()
_C.MODEL.MISSFORMER.TOKEN_MLP_MODE = "mix_skip"
_C.MODEL.MISSFORMER.HEADS = [1, 2, 5, 8]
_C.MODEL.MISSFORMER.REDUCTION_RATIOS = [8, 4, 2, 1]
_C.MODEL.MISSFORMER.BRIDGE_REDUCTION_RATIOS = [1, 2, 4, 8]
_C.MODEL.MISSFORMER.IN_OUT_CHAN = [[32, 64], [144, 128], [288, 320], [512, 512]]
_C.MODEL.MISSFORMER.DIMS = [64, 128, 320, 512]
_C.MODEL.MISSFORMER.LAYERS = [2, 2, 2, 2]
_C.MODEL.MISSFORMER.D_BASE_FEAT_SIZE = 3
_C.MODEL.MISSFORMER.D_BASE_DEPTH_SIZE = 1
_C.MODEL.MISSFORMER.KERNEL_SIZES = [7, 3, 3, 3]
_C.MODEL.MISSFORMER.STRIDES = [4, 2, 2, 2]
_C.MODEL.MISSFORMER.PADDING_SIZES = [3, 1, 1, 1]


_C.MODEL.SWIN_TRANSFORMER = CN()
_C.MODEL.SWIN_TRANSFORMER.MODEL = CN()
_C.MODEL.SWIN_TRANSFORMER.MODEL.TYPE = "swin"
_C.MODEL.SWIN_TRANSFORMER.MODEL.NAME = "swin_tiny_patch4_window7_224"
_C.MODEL.SWIN_TRANSFORMER.MODEL.PRETRAINED = ""
_C.MODEL.SWIN_TRANSFORMER.MODEL.RESUME = ""
_C.MODEL.SWIN_TRANSFORMER.MODEL.NUM_CLASSES = 1
_C.MODEL.SWIN_TRANSFORMER.MODEL.DROP_RATE = 0.0
_C.MODEL.SWIN_TRANSFORMER.MODEL.DROP_PATH_RATE = 0.1
_C.MODEL.SWIN_TRANSFORMER.MODEL.LABEL_SMOOTHING = 0.1

# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN = CN()
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.PATCH_SIZE = 4
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.IN_CHANS = 3
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.EMBED_DIM = 96
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.DEPTHS = [2, 2, 6, 2]
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.NUM_HEADS = [3, 6, 12, 24]
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.WINDOW_SIZE = 7
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.MLP_RATIO = 4.0
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.QKV_BIAS = True
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.QK_SCALE = None
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.APE = False
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.PATCH_NORM = True
# _C.MODEL.SWIN_TRANSFORMER.MODEL.SWIN.ELEMENTWISE_AFFINE = True

_C.MONAI = CN()
_C.MONAI.NAME = "VESSEL"
_C.MONAI.JSON_PATH = "config/monai.json"
_C.MONAI.TRANSFORMS = CN()
_C.MONAI.TRANSFORMS.KEYS = ["image", "label"]
_C.MONAI.TRANSFORMS.SPACING = (1.5, 1.5, 2.0)
_C.MONAI.TRANSFORMS.WINDOW = [-175.0, 250.0]
_C.MONAI.TRANSFORMS.CLIP = True
_C.MONAI.TRANSFORMS.ROI = (96, 96, 96)
_C.MONAI.TRANSFORMS.RAND = CN()
_C.MONAI.TRANSFORMS.RAND.FILP_PROB = 0.2
_C.MONAI.TRANSFORMS.RAND.SCALE_PROB = 0.1
_C.MONAI.TRANSFORMS.RAND.SHIFT_PROB = 0.1
_C.MONAI.TRANSFORMS.INFER_OVERLAP = 0.5
